echo ""
echo ""
echo "    ⚙️  Fetching for status.lol"
echo "    ⭐ Created post on Micro.blog!"
echo "    ⭐ Created post on Mastodon!"
echo "    ⚙️  Fetching for Letterboxd"
echo "    ⭐ Created post on Micro.blog!"
echo "    ⚙️  Fetching for Nexus"
echo "    ❎ No new items found for Nexus"
echo ""
echo ""
